www/tryit/config/routes.rb
Rails.application.routes.draw do
  resources :blade_reviews
  resources :blades
  resources :razors
  devise_for :users
  resources :notes
  resources :things
  root 'blades#index'
end

www/tryit/app/models/razor.rb
class Razor < ActiveRecord::Base
  has_many :blade_reviews
  belongs_to :user
end

www/tryit/app/controllers/razors_controller.rb
class RazorsController < ApplicationController
  before_action :set_razor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /razors
  # GET /razors.json
  def index
    @razors = current_user.razors
  end

  # GET /razors/1
  # GET /razors/1.json
  def show
  end

  # GET /razors/new
  def new
    @razor = Razor.new
  end

  # GET /razors/1/edit
  def edit
  end

  # POST /razors
  # POST /razors.json
  def create
    @razor = Razor.new(razor_params)
    @razor.user = current_user

    respond_to do |format|
      if @razor.save
        format.html { redirect_to razors_path, notice: 'Razor was successfully created.' }
        format.json { render :show, status: :created, location: @razor }
      else
        format.html { render :new }
        format.json { render json: @razor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /razors/1
  # PATCH/PUT /razors/1.json
  def update
    respond_to do |format|
      if @razor.update(razor_params)
        format.html { redirect_to @razor, notice: 'Razor was successfully updated.' }
        format.json { render :show, status: :ok, location: @razor }
      else
        format.html { render :edit }
        format.json { render json: @razor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /razors/1
  # DELETE /razors/1.json
  def destroy
    @razor.destroy
    respond_to do |format|
      format.html { redirect_to razors_url, notice: 'Razor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_razor
      @razor = Razor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def razor_params
      params.require(:razor).permit(:name)
    end
end

www/tryit/app/helpers/razors_helper.rb
module RazorsHelper
end

www/tryit/app/views/razors/_form.html.erb
<%= form_for @razor, :html => { :class => "form-horizontal razor" } do |f| %>

    <% if @razor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@razor.errors.count, "error") %> prohibited this razor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @razor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@razor[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            razors_path, :class => 'btn btn-default' %>

<% end %>

www/tryit/app/views/razors/edit.html.erb
<%- model_class = Razor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

www/tryit/app/views/razors/index.html.erb
<%- model_class = Razor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @razors.each do |razor| %>
      <tr>
        <td><%= link_to(razor.name, razor_path(razor)) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_razor_path(razor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      razor_path(razor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_razor_path,
            :class => 'btn btn-primary' %>

www/tryit/app/views/razors/new.html.erb
<%- model_class = Razor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

www/tryit/app/views/razors/show.html.erb
<%- model_class = Razor -%>
<div class="page-header">
  <h1><%= @razor.name %></h1>
</div>

<% if @razor.blade_reviews.count > 0 %>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Date</th>
        <th>Blade</th>
        <th>Review</th>
    </tr>
    </thead>
    <tbody>
    <% @razor.blade_reviews.each do |blade_review| %>
      <tr>
          <% review_text = sanitize format_markdown(blade_review.text) %>
          <td><%= blade_review.date %></td>
          <td><%= link_to(blade_review.blade.name, blade_path(blade_review.blade)) %></td>
          <td><%= link_to(review_text, blade_review_path(blade_review)) %></td>
          <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_blade_review_path(blade_review), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          blade_review_path(blade_review),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
          </td>
      </tr>
    <% end %>
    </tbody>
</table>
<% else %>
  <p>You don't have any reviews yet.</p>
<% end %>


<%= link_to t('.back', :default => t("New Blade Review")), new_blade_review_path(razor_id: @razor.id), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")), edit_razor_path(@razor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              razor_path(@razor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>