www/tryit/config/routes.rb
Rails.application.routes.draw do
  resources :blade_reviews
  resources :blades
  resources :razors
  devise_for :users
  resources :notes
  resources :things
  root 'blades#index'
end

www/tryit/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :thing
end

www/tryit/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new(thing_id: params[:thing_id])
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:thing_id, :text)
    end
end

www/tryit/app/helpers/notes_helper.rb
module NotesHelper
end

www/tryit/app/views/notes/_form.html.erb
<%= form_for @note, :html => { :class => "form-horizontal note" } do |f| %>

    <% if @note.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
      <%= f.hidden_field :thing_id, value: @note.thing.id %>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, :class => 'form-control', rows: 10 %>
    </div>
    <%= error_span(@note[:text]) %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), notes_path, :class => 'btn btn-default' %>

<% end %>

www/tryit/app/views/notes/edit.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

www/tryit/app/views/notes/index.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:thing_id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to note.id, note_path(note) %></td>
        <td><%= note.thing_id %></td>
        <td><%= note.text %></td>
        <td><%=l note.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_note_path(note), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      note_path(note),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_note_path,
            :class => 'btn btn-primary' %>

www/tryit/app/views/notes/new.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

www/tryit/app/views/notes/show.html.erb
<%- model_class = Note -%>
<p>
<div><%= link_to "(#{@note.thing.name})", thing_path(@note.thing) %></div>
</p>
<div class="page-header">
  <strong><%=t '.title', :default => @note.created_at.to_s %></strong>
</div>


<dl class="dl-horizontal">
    <div>
        <div><%= sanitize format_markdown(@note.text) %></div>
    </div>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")), notes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_note_path(@note), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              note_path(@note),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>